name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.vercel_deploy.outputs.env_url }}
    permissions:
      contents: read
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel env (production)
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build (prebuilt artifacts)
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to production
        id: vercel_deploy
        run: |
          OUTPUT=$(npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep "^Production:" | cut -d' ' -f2)
          echo "env_url=${URL}" >> $GITHUB_OUTPUT


