name: Preview

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch != 'main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel env (preview)
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build (prebuilt artifacts)
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy preview
        run: npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

