name: Preview

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel env (preview)
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build (prebuilt artifacts)
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy preview
        run: npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

